version: "3.9"

services:
  frontend:
    container_name: infinity-frontend
    build:
      context: .
      dockerfile: ${DOCKERFILE:-main.Dockerfile}
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_IMAGE_BASE_URL: ${NEXT_PUBLIC_IMAGE_BASE_URL}
        NEXT_PUBLIC_STRAPI_TOKEN: ${NEXT_PUBLIC_STRAPI_TOKEN}
    env_file:
      - ${ENV_FILE:-main.env}
    ports:
      - "${HOST_PORT:-3000}:3000"
    restart: unless-stopped
