services:
  frontend:
    image: ghcr.io/belforzedse/infinity-frontend:${IMAGE_TAG:-main}
    env_file:
      - ${ENV_FILE:-main.env}
    ports:
      - "${HOST_PORT:-80}:3000"
    restart: unless-stopped
    networks:
      - infinity-frontend-net

networks:
  infinity-frontend-net:
    driver: bridge
