version: "3"

services:
  # strapi:
  #   container_name: infinity-strapi
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     DATABASE_CLIENT: ${DATABASE_CLIENT}
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     NODE_ENV: development
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - infinity-network

  postgres:
    container_name: infinity-postgres
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - infinity-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - infinity-network

volumes:
  infinity-data:

networks:
  infinity-network:
    driver: bridge
